plugin: aws_ec2
regions:
  - us-east-1
hostnames:
    - name: 'instance-id'
filters:
  instance-state-name : running
  tag:db: postgres
profile: aws-profile
allow_duplicated_hosts: false

keyed_groups:
  - key: tags.Name
    prefix: hosts
    include:
      - "Postgres-Master"
      - "Postgres-Standby"
