# playbook.yml
---
- hosts: aws_ec2
  become: true
  vars:
    ansible_connection: aws_ssm             # set the connection to AWS SSM
    ansible_aws_ssm_bucket_name: my-terraform-state-files-buckets-1
    ansible_aws_ssm_region: us-east-1       # match the region in your inventory

  roles:
    - role: postgres

